###################### Metricbeat Configuration Example #######################

# This file is an example configuration file highlighting only the most common
# options. The metricbeat.full.yml file from the same directory contains all the
# supported options with more comments. You can use it as a reference.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/metricbeat/index.html

#==========================  Modules configuration ============================
nvidiadockerbeat.modules:

#---------------------------- nvidiadocker Module ----------------------------
- module: nvidiadocker
  metricsets: ["status"]
  enabled: true
  period: 10s
  hosts: ["localhost"]
  apiurl: "http://localhost:3476"
  dockerendpoint: "unix:///var/run/docker.sock"

